# Form implementation generated from reading ui file '.\ui\app_widget.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(430, 86)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_20 = QtWidgets.QWidget(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_20.sizePolicy().hasHeightForWidth())
        self.widget_20.setSizePolicy(sizePolicy)
        self.widget_20.setStyleSheet("background-color: rgb(34, 40, 49);")
        self.widget_20.setObjectName("widget_20")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_20)
        self.horizontalLayout_5.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.icon_app = QtWidgets.QPushButton(parent=self.widget_20)
        self.icon_app.setMaximumSize(QtCore.QSize(80, 16777215))
        self.icon_app.setStyleSheet("border:0px")
        self.icon_app.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\ui\\../../../../../_apps/Agent_Studio/icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.icon_app.setIcon(icon)
        self.icon_app.setIconSize(QtCore.QSize(80, 80))
        self.icon_app.setObjectName("icon_app")
        self.horizontalLayout_5.addWidget(self.icon_app)
        self.widget_21 = QtWidgets.QWidget(parent=self.widget_20)
        self.widget_21.setObjectName("widget_21")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.widget_21)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.app_name = QtWidgets.QLabel(parent=self.widget_21)
        self.app_name.setObjectName("app_name")
        self.verticalLayout_22.addWidget(self.app_name)
        self.widget_23 = QtWidgets.QWidget(parent=self.widget_21)
        self.widget_23.setObjectName("widget_23")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_23)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.run_btn = QtWidgets.QPushButton(parent=self.widget_23)
        self.run_btn.setMaximumSize(QtCore.QSize(30, 30))
        self.run_btn.setStyleSheet("QPushButton {\n"
"    border:0px;\n"
"    background-color: rgb(67, 79, 97)\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 62, 70);\n"
"}")
        self.run_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\ui\\../sources/play.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.run_btn.setIcon(icon1)
        self.run_btn.setIconSize(QtCore.QSize(30, 30))
        self.run_btn.setObjectName("run_btn")
        self.horizontalLayout_4.addWidget(self.run_btn)
        self.delete_btn = QtWidgets.QPushButton(parent=self.widget_23)
        self.delete_btn.setMaximumSize(QtCore.QSize(30, 30))
        self.delete_btn.setStyleSheet("QPushButton {\n"
"    border:0px;\n"
"    background-color: rgb(67, 79, 97)\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 62, 70);\n"
"}")
        self.delete_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(".\\ui\\../sources/delete.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.delete_btn.setIcon(icon2)
        self.delete_btn.setIconSize(QtCore.QSize(30, 30))
        self.delete_btn.setObjectName("delete_btn")
        self.horizontalLayout_4.addWidget(self.delete_btn)
        self.info_btn = QtWidgets.QPushButton(parent=self.widget_23)
        self.info_btn.setMaximumSize(QtCore.QSize(30, 30))
        self.info_btn.setStyleSheet("QPushButton {\n"
"    border:0px;\n"
"    background-color: rgb(67, 79, 97)\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 62, 70);\n"
"}")
        self.info_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(".\\ui\\../sources/info.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.info_btn.setIcon(icon3)
        self.info_btn.setIconSize(QtCore.QSize(30, 30))
        self.info_btn.setObjectName("info_btn")
        self.horizontalLayout_4.addWidget(self.info_btn)
        self.verticalLayout_22.addWidget(self.widget_23)
        self.horizontalLayout_5.addWidget(self.widget_21)
        self.horizontalLayout.addWidget(self.widget_20)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.app_name.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600; color:#ffffff;\">AGENT STUDIO</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
