# Form implementation generated from reading ui file '.\ui\main.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(550, 683)
        Form.setMaximumSize(QtCore.QSize(550, 16777215))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setStyleSheet("background-color: #222831;\n"
"border-radius:8px;")
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_2 = QtWidgets.QWidget(parent=self.widget)
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 80))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(parent=self.widget_2)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.tabWidget = QtWidgets.QTabWidget(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setStyleSheet("QTabWidget::pane {\n"
"        border: 0px;\n"
"        background: transparent;\n"
"    }\n"
"    QTabBar::tab {\n"
"        background: rgb(34, 40, 49);\n"
"        color: white;\n"
"        padding: 8px;\n"
"        border-radius:8px;\n"
"    }\n"
"    QTabBar::tab:selected {\n"
"        background: rgb(94, 111, 136);\n"
"    }")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(9)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget_4 = QtWidgets.QWidget(parent=self.tab_3)
        self.widget_4.setStyleSheet("background-color: #5e6f88;")
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_17 = QtWidgets.QWidget(parent=self.widget_4)
        self.widget_17.setObjectName("widget_17")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget_17)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_4 = QtWidgets.QLabel(parent=self.widget_17)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_12.addWidget(self.label_4)
        self.path_input = QtWidgets.QLineEdit(parent=self.widget_17)
        self.path_input.setMinimumSize(QtCore.QSize(0, 35))
        self.path_input.setMaximumSize(QtCore.QSize(16777215, 35))
        self.path_input.setStyleSheet("background-color: #FFF8F8;\n"
"color: rgb(34, 40, 49);\n"
" padding: 5px;\n"
"")
        self.path_input.setObjectName("path_input")
        self.verticalLayout_12.addWidget(self.path_input)
        self.verticalLayout_4.addWidget(self.widget_17)
        self.installButton = QtWidgets.QPushButton(parent=self.widget_4)
        self.installButton.setMinimumSize(QtCore.QSize(0, 30))
        self.installButton.setMaximumSize(QtCore.QSize(16777215, 30))
        self.installButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(34, 40, 49);\n"
"color:rgb(255, 255, 255)\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 62, 70);\n"
"}")
        self.installButton.setObjectName("installButton")
        self.verticalLayout_4.addWidget(self.installButton)
        self.verticalLayout_6.addWidget(self.widget_4)
        self.widget_11 = QtWidgets.QWidget(parent=self.tab_3)
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_11)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_6.addWidget(self.widget_11)
        self.widget_3 = QtWidgets.QWidget(parent=self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setStyleSheet("background-color: rgb(94, 111, 136);")
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 532, 434))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_5.addWidget(self.scrollArea)
        self.verticalLayout_6.addWidget(self.widget_3)
        self.tabWidget.addTab(self.tab_3, "")
        self.BUILD_APP = QtWidgets.QWidget()
        self.BUILD_APP.setObjectName("BUILD_APP")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.BUILD_APP)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.widget_8 = QtWidgets.QWidget(parent=self.BUILD_APP)
        self.widget_8.setStyleSheet("background-color: #5e6f88;")
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_7 = QtWidgets.QLabel(parent=self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_11.addWidget(self.label_7)
        self.widget_13 = QtWidgets.QWidget(parent=self.widget_8)
        self.widget_13.setObjectName("widget_13")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_13)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.selectApp = QtWidgets.QComboBox(parent=self.widget_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectApp.sizePolicy().hasHeightForWidth())
        self.selectApp.setSizePolicy(sizePolicy)
        self.selectApp.setMinimumSize(QtCore.QSize(0, 35))
        self.selectApp.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.selectApp.setStyleSheet("QComboBox {\n"
"background-color: #FFF8F8;\n"
"    color: rgb(34, 40, 49);\n"
"    border-radius: 5px;\n"
"     padding: 5px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"     color: rgb(34, 40, 49);\n"
"    border-radius: 0px; /* Set border radius to 0px */\n"
" padding: 5px;\n"
"}\n"
"")
        self.selectApp.setObjectName("selectApp")
        self.selectApp.addItem("")
        self.selectApp.addItem("")
        self.horizontalLayout.addWidget(self.selectApp)
        self.appName = QtWidgets.QLineEdit(parent=self.widget_13)
        self.appName.setMinimumSize(QtCore.QSize(0, 35))
        self.appName.setMaximumSize(QtCore.QSize(16777215, 35))
        self.appName.setStyleSheet("background-color: #FFF8F8;\n"
"color: rgb(34, 40, 49);\n"
" padding: 5px;\n"
"")
        self.appName.setObjectName("appName")
        self.horizontalLayout.addWidget(self.appName)
        self.verticalLayout_11.addWidget(self.widget_13)
        self.verticalLayout_10.addWidget(self.widget_8)
        self.widget_5 = QtWidgets.QWidget(parent=self.BUILD_APP)
        self.widget_5.setStyleSheet("background-color: #5e6f88;")
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_5 = QtWidgets.QLabel(parent=self.widget_5)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_5.setObjectName("label_5")
        self.verticalLayout_7.addWidget(self.label_5)
        self.appFolder = QtWidgets.QLineEdit(parent=self.widget_5)
        self.appFolder.setMinimumSize(QtCore.QSize(0, 35))
        self.appFolder.setMaximumSize(QtCore.QSize(16777215, 35))
        self.appFolder.setStyleSheet("background-color: #FFF8F8;\n"
"color: rgb(34, 40, 49);\n"
" padding: 5px;\n"
"")
        self.appFolder.setObjectName("appFolder")
        self.verticalLayout_7.addWidget(self.appFolder)
        self.verticalLayout_10.addWidget(self.widget_5)
        self.widget_6 = QtWidgets.QWidget(parent=self.BUILD_APP)
        self.widget_6.setStyleSheet("background-color: #5e6f88;")
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_6 = QtWidgets.QLabel(parent=self.widget_6)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_6.setObjectName("label_6")
        self.verticalLayout_8.addWidget(self.label_6)
        self.outputFolder = QtWidgets.QLineEdit(parent=self.widget_6)
        self.outputFolder.setMinimumSize(QtCore.QSize(0, 35))
        self.outputFolder.setMaximumSize(QtCore.QSize(16777215, 35))
        self.outputFolder.setStyleSheet("background-color: #FFF8F8;\n"
"color: rgb(34, 40, 49);\n"
" padding: 5px;\n"
"")
        self.outputFolder.setObjectName("outputFolder")
        self.verticalLayout_8.addWidget(self.outputFolder)
        self.verticalLayout_10.addWidget(self.widget_6)
        self.widget_14 = QtWidgets.QWidget(parent=self.BUILD_APP)
        self.widget_14.setStyleSheet("background-color: #5e6f88;")
        self.widget_14.setObjectName("widget_14")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.widget_14)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_2 = QtWidgets.QLabel(parent=self.widget_14)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_16.addWidget(self.label_2)
        self.widget_15 = QtWidgets.QWidget(parent=self.widget_14)
        self.widget_15.setObjectName("widget_15")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_15)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.python_mode = QtWidgets.QRadioButton(parent=self.widget_15)
        self.python_mode.setStyleSheet("color: rgb(255, 255, 255);")
        self.python_mode.setObjectName("python_mode")
        self.horizontalLayout_2.addWidget(self.python_mode)
        self.p_compile_mode = QtWidgets.QRadioButton(parent=self.widget_15)
        self.p_compile_mode.setStyleSheet("color: rgb(255, 255, 255);")
        self.p_compile_mode.setObjectName("p_compile_mode")
        self.horizontalLayout_2.addWidget(self.p_compile_mode)
        self.verticalLayout_16.addWidget(self.widget_15)
        self.buildBtn = QtWidgets.QPushButton(parent=self.widget_14)
        self.buildBtn.setMinimumSize(QtCore.QSize(0, 30))
        self.buildBtn.setMaximumSize(QtCore.QSize(16777215, 30))
        self.buildBtn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(34, 40, 49);\n"
"color:rgb(255, 255, 255)\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 62, 70);\n"
"}")
        self.buildBtn.setObjectName("buildBtn")
        self.verticalLayout_16.addWidget(self.buildBtn)
        self.verticalLayout_10.addWidget(self.widget_14)
        self.widget_7 = QtWidgets.QWidget(parent=self.BUILD_APP)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_7.sizePolicy().hasHeightForWidth())
        self.widget_7.setSizePolicy(sizePolicy)
        self.widget_7.setStyleSheet("background-color: #5e6f88;")
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(parent=self.widget_7)
        self.plainTextEdit.setStyleSheet("background-color: #FFF8F8;\n"
"color: rgb(34, 40, 49);\n"
" padding: 5px;\n"
"color:rgb(0, 0, 0)\n"
"")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout_9.addWidget(self.plainTextEdit)
        self.verticalLayout_10.addWidget(self.widget_7)
        self.tabWidget.addTab(self.BUILD_APP, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(9)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.widget_9 = QtWidgets.QWidget(parent=self.tab_4)
        self.widget_9.setStyleSheet("background-color: #5e6f88;")
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_8 = QtWidgets.QLabel(parent=self.widget_9)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_8.setObjectName("label_8")
        self.verticalLayout_13.addWidget(self.label_8)
        self.private_rsa = QtWidgets.QLineEdit(parent=self.widget_9)
        self.private_rsa.setMinimumSize(QtCore.QSize(0, 35))
        self.private_rsa.setMaximumSize(QtCore.QSize(16777215, 35))
        self.private_rsa.setStyleSheet("background-color: #FFF8F8;\n"
"color: rgb(34, 40, 49);\n"
" padding: 5px;\n"
"")
        self.private_rsa.setObjectName("private_rsa")
        self.verticalLayout_13.addWidget(self.private_rsa)
        self.verticalLayout_15.addWidget(self.widget_9, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.widget_10 = QtWidgets.QWidget(parent=self.tab_4)
        self.widget_10.setStyleSheet("background-color: #5e6f88;")
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.widget_10)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_9 = QtWidgets.QLabel(parent=self.widget_10)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_9.setObjectName("label_9")
        self.verticalLayout_14.addWidget(self.label_9)
        self.public_rsa = QtWidgets.QLineEdit(parent=self.widget_10)
        self.public_rsa.setMinimumSize(QtCore.QSize(0, 35))
        self.public_rsa.setMaximumSize(QtCore.QSize(16777215, 35))
        self.public_rsa.setStyleSheet("background-color: #FFF8F8;\n"
"color: rgb(34, 40, 49);\n"
" padding: 5px;\n"
"")
        self.public_rsa.setObjectName("public_rsa")
        self.verticalLayout_14.addWidget(self.public_rsa)
        self.verticalLayout_15.addWidget(self.widget_10)
        self.generateBtn = QtWidgets.QPushButton(parent=self.tab_4)
        self.generateBtn.setMinimumSize(QtCore.QSize(0, 30))
        self.generateBtn.setMaximumSize(QtCore.QSize(16777215, 30))
        self.generateBtn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(94, 111, 136);\n"
"color:rgb(255, 255, 255)\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 62, 70);\n"
"}")
        self.generateBtn.setObjectName("generateBtn")
        self.verticalLayout_15.addWidget(self.generateBtn)
        self.exportBtn = QtWidgets.QPushButton(parent=self.tab_4)
        self.exportBtn.setMinimumSize(QtCore.QSize(0, 30))
        self.exportBtn.setMaximumSize(QtCore.QSize(16777215, 30))
        self.exportBtn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(94, 111, 136);\n"
"color:rgb(255, 255, 255)\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 62, 70);\n"
"}")
        self.exportBtn.setObjectName("exportBtn")
        self.verticalLayout_15.addWidget(self.exportBtn)
        self.widget_20 = QtWidgets.QWidget(parent=self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_20.sizePolicy().hasHeightForWidth())
        self.widget_20.setSizePolicy(sizePolicy)
        self.widget_20.setStyleSheet("background-color: #5e6f88;")
        self.widget_20.setObjectName("widget_20")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.widget_20)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_10 = QtWidgets.QLabel(parent=self.widget_20)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_10.setObjectName("label_10")
        self.verticalLayout_20.addWidget(self.label_10)
        self.logsText = QtWidgets.QPlainTextEdit(parent=self.widget_20)
        self.logsText.setStyleSheet("background-color: #FFF8F8;\n"
"color: rgb(34, 40, 49);\n"
" padding: 5px;\n"
"color:rgb(0, 0, 0)\n"
"")
        self.logsText.setObjectName("logsText")
        self.verticalLayout_20.addWidget(self.logsText)
        self.verticalLayout_15.addWidget(self.widget_20)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.widget_16 = QtWidgets.QWidget(parent=self.tab)
        self.widget_16.setStyleSheet("background-color: #5e6f88;")
        self.widget_16.setObjectName("widget_16")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.widget_16)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.widget_18 = QtWidgets.QWidget(parent=self.widget_16)
        self.widget_18.setObjectName("widget_18")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.widget_18)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.pushButton = QtWidgets.QPushButton(parent=self.widget_18)
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\ui\\../sources/app.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(100, 100))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_19.addWidget(self.pushButton)
        self.label_3 = QtWidgets.QLabel(parent=self.widget_18)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_19.addWidget(self.label_3)
        self.verticalLayout_18.addWidget(self.widget_18)
        self.widget_19 = QtWidgets.QWidget(parent=self.widget_16)
        self.widget_19.setObjectName("widget_19")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_19)
        self.horizontalLayout_3.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_3.setSpacing(3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gitBtn = QtWidgets.QPushButton(parent=self.widget_19)
        self.gitBtn.setMinimumSize(QtCore.QSize(0, 40))
        self.gitBtn.setMaximumSize(QtCore.QSize(40, 40))
        self.gitBtn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.gitBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\ui\\../sources/github.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.gitBtn.setIcon(icon1)
        self.gitBtn.setIconSize(QtCore.QSize(30, 30))
        self.gitBtn.setObjectName("gitBtn")
        self.horizontalLayout_3.addWidget(self.gitBtn)
        self.linkBtn = QtWidgets.QPushButton(parent=self.widget_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.linkBtn.sizePolicy().hasHeightForWidth())
        self.linkBtn.setSizePolicy(sizePolicy)
        self.linkBtn.setMinimumSize(QtCore.QSize(0, 40))
        self.linkBtn.setMaximumSize(QtCore.QSize(40, 40))
        self.linkBtn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.linkBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(".\\ui\\../sources/linkedin.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.linkBtn.setIcon(icon2)
        self.linkBtn.setIconSize(QtCore.QSize(30, 30))
        self.linkBtn.setObjectName("linkBtn")
        self.horizontalLayout_3.addWidget(self.linkBtn)
        self.verticalLayout_18.addWidget(self.widget_19)
        self.verticalLayout_17.addWidget(self.widget_16, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.tabWidget.addTab(self.tab, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">PYTHON BROADCAST</span></p></body></html>"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">INSTALL APP</span></p></body></html>"))
        self.installButton.setText(_translate("Form", "INSTALL"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "INSTALATION"))
        self.label_7.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">SELECT APP</span></p></body></html>"))
        self.selectApp.setItemText(0, _translate("Form", "SELECT"))
        self.selectApp.setItemText(1, _translate("Form", "NEW"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">APP FOLDER</span></p></body></html>"))
        self.label_6.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">OUPUT DIR</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">BUILD MODE</span></p></body></html>"))
        self.python_mode.setText(_translate("Form", "Python code"))
        self.p_compile_mode.setText(_translate("Form", "Pre-compile code"))
        self.buildBtn.setText(_translate("Form", "BUILD"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.BUILD_APP), _translate("Form", "BUILD APP"))
        self.label_8.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">RSA INSTALLER</span></p></body></html>"))
        self.label_9.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">RSA BUILDER</span></p></body></html>"))
        self.generateBtn.setText(_translate("Form", "GENERATE KEYS"))
        self.exportBtn.setText(_translate("Form", "EXPORT"))
        self.label_10.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">LOGS</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "CONFIG"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">v1.0.0<br/><br/>Tarcisio Prates<br/>2025</span><span style=\" font-size:14pt; font-weight:600; color:#222831;\"><br/></span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Info"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
